# Generated by Django 5.0.7 on 2024-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),  # type: ignore
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={
                ("email", "first_name"),
                ("email", "last_name"),
                ("first_name", "last_name"),
            },
        ),
    ]
